import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.account_management': 'Quản lý tài khoản',
    'nav.news': 'Tin tức',
    'nav.analysis': 'Phân tích',
    'nav.community': 'Cộng đồng',
    'nav.investment_management': 'Quản lý đầu tư',
    'nav.investment_utilities': 'Tiện ích đầu tư',
    'nav.investment_guide': 'Hướng dẫn đầu tư',
    'nav.contact': 'Liên hệ',
    'nav.packages': 'Gói đầu tư',
    'nav.investment': 'Đầu tư',
    
    // Hero Section
    'hero.title': 'Đầu tư Bitcoin Thông minh với AI',
    'hero.title.highlight': 'Thông minh',
    'hero.title.suffix': 'với AI',
    'hero.description': 'Nền tảng đầu tư Bitcoin hàng đầu Việt Nam với công nghệ AI dự báo, phân tích chuyên sâu và cập nhật real-time 24/7.',
    'hero.cta.invest': 'Bắt đầu đầu tư',
    'hero.cta.demo': 'Xem demo AI',
    'hero.feature.security': 'Bảo mật tuyệt đối',
    'hero.feature.ai': 'AI dự báo chính xác',
    'hero.feature.realtime': 'Cập nhật 24/7',
    'hero.price.title': 'Giá Bitcoin hiện tại',
    'hero.ai.prediction': 'Dự báo AI (7 ngày)',
    'hero.ai.confidence': 'Độ tin cậy:',
    
    // Investment Calculator
    'calc.title': 'Máy tính đầu tư thông minh',
    'calc.description': 'Tính toán lợi nhuận đầu tư Bitcoin với AI dự báo và phân tích rủi ro tự động',
    'calc.form.title': 'Tính toán đầu tư',
    'calc.form.amount': 'Số tiền đầu tư (VNĐ)',
    'calc.form.duration': 'Thời gian đầu tư',
    'calc.form.package': 'Gói đầu tư',
    'calc.risk.level': 'Mức độ rủi ro',
    'calc.results.title': 'Kết quả dự báo',
    'calc.results.investment': 'Tổng đầu tư',
    'calc.results.profit': 'Lợi nhuận ước tính',
    'calc.results.total': 'Tổng nhận về',
    'calc.ai.trend': 'Xu hướng tăng mạnh',
    'calc.ai.confidence': 'Độ tin cậy: 89%',
    'calc.cta': 'Bắt đầu đầu tư ngay',
    
    // Investment Section
    'investment.title': 'Đầu tư Bitcoin thông minh',
    'investment.description': 'Khám phá các gói đầu tư và theo dõi hiệu quả của cộng đồng nhà đầu tư',
    'investment.tabs.packages': 'Gói đầu tư',
    'investment.tabs.investors': 'Nhà đầu tư',
    
    // Investment Packages
    'packages.title': 'Gói đầu tư HHDcoin',
    'packages.description': 'Chọn gói đầu tư phù hợp với mục tiêu tài chính của bạn',
    'packages.popular': 'PHỔ BIẾN NHẤT',
    'packages.profit': 'Lợi nhuận/năm',
    'packages.select': 'Chọn gói này',
    
    // Contact
    'contact.title': 'Liên hệ & Hỗ trợ',
    'contact.description': 'Đội ngũ chuyên gia HHDcoin luôn sẵn sàng hỗ trợ bạn 24/7',
    'contact.form.name': 'Họ và tên',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.subject': 'Chủ đề',
    'contact.form.message': 'Nội dung',
    'contact.form.send': 'Gửi tin nhắn',
    'contact.form.sending': 'Đang gửi...',
    
    // Investors
    'investors.title': 'Bảng thông tin nhà đầu tư',
    'investors.description': 'Theo dõi hiệu quả đầu tư và thành tích của các nhà đầu tư trên nền tảng HHDcoin',
    'investors.stats.total': 'Tổng nhà đầu tư',
    'investors.stats.investment': 'Tổng đầu tư',
    'investors.stats.profit': 'Tổng lợi nhuận',
    'investors.table.name': 'Họ và tên',
    'investors.table.email': 'Email',
    'investors.table.phone': 'Số điện thoại',
    'investors.table.amount': 'Số tiền đầu tư',
    'investors.table.time': 'Thời gian',
    'investors.table.bitcoin': 'Mã Bitcoin',
    'investors.table.currentValue': 'Giá trị hiện tại',
    'investors.table.profit': 'Lãi/Lỗ',
    'investors.table.percentage': 'Phần trăm',
    'investors.table.status': 'Trạng thái',
    'investors.status.active': 'Hoạt động',
    'investors.status.inactive': 'Không hoạt động',
    
    // News Section
    'news.title': 'Tin tức mới nhất',
    'news.bitcoin_title': 'Bitcoin tăng giá mạnh',
    'news.ai_title': 'AI dự báo xu hướng giảm nhẹ',
    'news.mobile_title': 'HHDcoin ra mắt app mobile',
    'news.bitcoin_surge': 'Bitcoin tăng giá mạnh: Giá BTC vượt mốc $125.000 lần đầu tiên trong năm 2025 nhờ lực mua từ các tổ chức lớn.',
    'news.ai_prediction': 'AI dự báo xu hướng giảm nhẹ: Mô hình AI cho thấy xác suất điều chỉnh giá trong 3 ngày tới lên tới 63%.',
    'news.mobile_app': 'HHDcoin ra mắt phiên bản app mobile: Ứng dụng đầu tư Bitcoin tích hợp AI đã có mặt trên iOS và Android.',
    
    // Analytics Page
    'analytics.title': 'Phân tích',
    'analytics.investment_chart': 'Biểu đồ đầu tư: AI sẽ phân tích xu hướng tăng trưởng, khuyến nghị đầu tư và rủi ro dựa trên dữ liệu mới nhất.',
    'analytics.market_share': 'Biểu đồ thị phần: So sánh phần trăm đầu tư giữa các đồng coin và tổng danh mục của bạn.',
    'analytics.interest_rate': 'Phân tích lãi suất: Tự động đánh giá hiệu suất theo lãi suất %/tháng.',
    
    
    
    // Community Page
    'community.join_title': 'Đăng ký tham gia cộng đồng HHDcoin',
    'community.form.full_name': 'Họ và tên',
    'community.form.email': 'Email',
    'community.form.phone': 'Số điện thoại',
    'community.form.zalo': 'Liên hệ qua Zalo',
    'community.form.submit': 'Gửi đăng ký',
    'community.title': 'Cộng đồng đầu tư HHDcoin',
    'community.description': 'Kết nối với cộng đồng nhà đầu tư Bitcoin, chia sẻ kinh nghiệm và học hỏi từ các chuyên gia',
    'community.stats.total_members': 'Tổng thành viên',
    'community.stats.active_today': 'Hoạt động hôm nay',
    'community.stats.total_discussions': 'Tổng thảo luận',
    'community.add_member': 'Thêm thành viên',
    'community.add_member_dialog_title': 'Thêm thành viên mới',
    'community.search_placeholder': 'Tìm kiếm thành viên...',
    'community.filter_experience': 'Lọc theo kinh nghiệm',
    'community.filter_member_level': 'Lọc theo cấp độ',
    'community.clear_filters': 'Xóa bộ lọc',
    'community.experience.beginner': 'Người mới',
    'community.experience.intermediate': 'Trung cấp',
    'community.experience.advanced': 'Nâng cao',
    'community.experience.expert': 'Chuyên gia',
    'community.member_level.bronze': 'Đồng',
    'community.member_level.silver': 'Bạc',
    'community.member_level.gold': 'Vàng',
    'community.member_level.diamond': 'Kim cương',
    'community.form.job_title': 'Chức vụ',
    'community.form.company': 'Công ty',
    'community.form.location': 'Địa điểm',
    'community.form.experience_level': 'Mức độ kinh nghiệm',
    'community.form.member_level': 'Cấp độ thành viên',
    'community.form.interests': 'Sở thích',
    'community.form.bio': 'Giới thiệu bản thân',
    'community.form.facebook_profile': 'Facebook cá nhân',
    'community.form.is_public_profile': 'Công khai hồ sơ',
    'community.form.newsletter': 'Nhận tin tức',
    'community.success.member_added': 'Thành viên mới đã được thêm vào cộng đồng!',
    'community.success.member_deleted': 'Thành viên đã được xóa khỏi cộng đồng',
    'community.error.add_member': 'Có lỗi xảy ra khi thêm thành viên mới',
    'community.error.delete_member': 'Có lỗi xảy ra khi xóa thành viên',
    'community.button.cancel': 'Hủy',
    'community.button.adding': 'Đang thêm...',
    'community.button.add_member': 'Thêm thành viên',
    'community.button.contact_zalo': 'Liên hệ Zalo',
    'community.button.edit': 'Chỉnh sửa',
    'community.button.delete': 'Xóa',
    'community.button.message': 'Nhắn tin',
    'community.loading': 'Đang tải cộng đồng...',
    'community.no_members': 'Chưa có thành viên nào',
    
    // Community - Additional missing translations
    'community.form.occupation': 'Nghề nghiệp',
    'community.form.bio_label': 'Giới thiệu bản thân',
    'community.social_media_title': 'Thông tin mạng xã hội',
    'community.facebook_url': 'Facebook URL',
    'community.zalo_phone': 'Zalo (Số điện thoại)',
    'community.placeholder.search_members': 'Tìm kiếm thành viên...',
    'community.placeholder.experience_level': 'Mức độ kinh nghiệm',
    'community.placeholder.member_level': 'Cấp độ thành viên',
    'community.placeholder.all': 'Tất cả',
    'community.loading_members': 'Đang tải danh sách thành viên...',
    'community.member.joined': 'Tham gia:',
    'community.member.interests': 'Sở thích:',
    'community.member.points': 'Điểm: ',
    'community.member.active': 'Đang hoạt động',
    'community.member.inactive': 'Không hoạt động',
    'community.no_members_found': 'Không tìm thấy thành viên',
    'community.no_members_hint': 'Thử thay đổi bộ lọc hoặc từ khóa tìm kiếm',
    'community.confirm_delete': 'Bạn có chắc chắn muốn xóa thành viên {{name}} khỏi cộng đồng?',
    'community.placeholder.full_name': 'Nguyễn Văn A',
    'community.placeholder.email': 'email@example.com',
    'community.placeholder.phone': '0987654321',
    'community.placeholder.location': 'Hà Nội',
    'community.placeholder.occupation': 'Kỹ sư phần mềm',
    'community.placeholder.bio': 'Chia sẻ về kinh nghiệm đầu tư và mục tiêu của bạn...',
    'community.placeholder.facebook': 'https://facebook.com/username',
    'community.placeholder.zalo': '0987654321',
    
    // Analysis Page
    'analysis.title': 'Phân tích AI & Thị trường',
    'analysis.description': 'Phân tích toàn diện với AI để đưa ra quyết định đầu tư thông minh và hiệu quả nhất',
    'analysis.features_title': 'Các tính năng phân tích',
    'analysis.investment_chart': 'Biểu đồ đầu tư',
    'analysis.market_share': 'Biểu đồ thị phần',
    'analysis.interest_rate_analysis': 'Phân tích lãi suất',
    'analysis.ai_insights': 'AI Insights & Analysis',
    'analysis.ai_description': 'Phân tích thị trường thông minh với công nghệ AI GPT-5',
    'analysis.refresh': 'Cập nhật',
    'analysis.market_analysis': 'Phân Tích Thị Trường AI',
    'analysis.trading_recommendations': 'Khuyến Nghị Giao Dịch',
    'analysis.sentiment_analysis': 'Phân Tích Cảm Xúc Tin Tức',
    'analysis.analyzing': 'Đang phân tích...',
    'analysis.confidence': 'Độ tin cậy:',
    'analysis.risk_level': 'Mức độ rủi ro:',
    'analysis.price_targets': 'Mục tiêu giá',
    'analysis.short_term': 'Ngắn hạn',
    'analysis.medium_term': 'Trung hạn',
    'analysis.key_factors': 'Yếu tố chính:',
    'analysis.ai_recommendation': 'Khuyến nghị AI',
    'analysis.analysis_type': 'Loại phân tích:',
    'analysis.updated': 'Cập nhật:',
    'analysis.login_required': 'Vui lòng đăng nhập để xem khuyến nghị giao dịch',
    'analysis.creating_recommendations': 'Đang tạo khuyến nghị...',
    'analysis.risk_profile': 'Hồ sơ rủi ro:',
    'analysis.conservative': 'Bảo thủ',
    'analysis.moderate': 'Vừa phải',
    'analysis.aggressive': 'Tích cực',
    'analysis.buy': 'MUA',
    'analysis.sell': 'BÁN', 
    'analysis.hold': 'GIỮ',
    'analysis.reasoning': 'Lý do:',
    'analysis.timeframe': 'Khung thời gian:',
    'analysis.bitcoin_price': 'Giá Bitcoin:',
    'analysis.change_24h': 'Thay đổi 24h:',
    'analysis.risk_assessment': 'Đánh giá rủi ro',
    'analysis.sentiment_login_required': 'Vui lòng đăng nhập để sử dụng phân tích cảm xúc',
    'analysis.news_input_label': 'Nhập tin tức hoặc bài viết về Bitcoin:',
    'analysis.news_placeholder': 'Dán nội dung tin tức, bài viết hoặc bình luận về Bitcoin để phân tích cảm xúc thị trường...',
    'analysis.analyze_sentiment': 'Phân tích cảm xúc',
    'analysis.analyzing_sentiment': 'Đang phân tích...',
    'analysis.sentiment_results': 'Kết quả phân tích:',
    'analysis.sentiment_summary': 'Tóm tắt:',
    'analysis.analyzed_at': 'Phân tích lúc:',
    'analysis.error_no_data': 'Không thể tải dữ liệu phân tích',
    'analysis.error_no_recommendations': 'Không thể tải khuyến nghị giao dịch',
    'analysis.toast.error_title': 'Lỗi',
    'analysis.toast.no_text': 'Vui lòng nhập văn bản để phân tích cảm xúc',
    'analysis.toast.analysis_complete': 'Phân tích hoàn thành',
    'analysis.toast.analysis_error': 'Lỗi phân tích',
    'analysis.toast.analysis_error_desc': 'Không thể phân tích cảm xúc. Vui lòng thử lại.',
    
    // Dashboard Page
    'dashboard.welcome': 'Chào mừng, {name}!',
    'dashboard.subtitle': 'Quản lý tài khoản và theo dõi đầu tư Bitcoin của bạn',
    'dashboard.admin': 'Admin',
    'dashboard.member': 'Member',
    'dashboard.logout': 'Đăng xuất',
    'dashboard.account_info': 'Thông tin tài khoản',
    'dashboard.email_not_updated': 'Chưa cập nhật email',
    'dashboard.current_bitcoin_price': 'Giá Bitcoin hiện tại',
    'dashboard.portfolio_value': 'Giá trị danh mục',
    'dashboard.no_investments': 'Chưa có khoản đầu tư nào',
    'dashboard.quick_actions': 'Thao tác nhanh',
    'dashboard.frequent_features': 'Các tính năng thường sử dụng',
    'dashboard.view_packages': 'Xem gói đầu tư',
    'dashboard.market_analysis': 'Phân tích thị trường',
    'dashboard.community': 'Cộng đồng',
    'dashboard.admin_panel': 'Quản lý hệ thống',
    'dashboard.account_settings': 'Cài đặt tài khoản',
    
    // Login Page
    'login.title': 'Đăng nhập HHDcoin',
    'login.subtitle': 'Truy cập vào tài khoản đầu tư Bitcoin của bạn',
    'login.username_label': 'Tài khoản',
    'login.username_placeholder': 'Nhập tài khoản của bạn',
    'login.password_label': 'Mật khẩu',
    'login.password_placeholder': 'Nhập mật khẩu của bạn',
    'login.login_button': 'Đăng nhập',
    'login.logging_in': 'Đang đăng nhập...',
    'login.or': 'Hoặc',
    'login.no_account': 'Chưa có tài khoản?',
    'login.register_now': 'Đăng ký ngay',
    'login.demo_accounts': 'Tài khoản demo:',
    'login.admin_demo': 'Admin:',
    'login.member_demo': 'Member:',
    'login.success_title': 'Đăng nhập thành công!',
    'login.success_description': 'Chào mừng bạn trở lại HHDcoin.',
    'login.username_min_error': 'Username phải có ít nhất 3 ký tự',
    'login.password_min_error': 'Password phải có ít nhất 6 ký tự',
    
    // Register Page
    'register.title': 'Đăng ký HHDcoin',
    'register.subtitle': 'Tạo tài khoản để bắt đầu đầu tư Bitcoin',
    'register.username_label': 'Tài khoản',
    'register.username_placeholder': 'Nhập tài khoản mong muốn',
    'register.password_label': 'Mật khẩu',
    'register.password_placeholder': 'Nhập mật khẩu',
    'register.confirm_password_label': 'Xác nhận mật khẩu',
    'register.confirm_password_placeholder': 'Nhập lại mật khẩu',
    'register.full_name_label': 'Họ và tên',
    'register.full_name_placeholder': 'Nhập họ tên đầy đủ',
    'register.email_label': 'Email (tùy chọn)',
    'register.email_placeholder': 'Nhập địa chỉ email',
    'register.register_button': 'Đăng ký',
    'register.registering': 'Đang đăng ký...',
    'register.or': 'Hoặc',
    'register.have_account': 'Đã có tài khoản?',
    'register.login_now': 'Đăng nhập ngay',
    'register.success_title': 'Đăng ký thành công!',
    'register.success_description': 'Chào mừng bạn đến với HHDcoin.',
    'register.username_min_error': 'Username phải có ít nhất 3 ký tự',
    'register.password_min_error': 'Password phải có ít nhất 6 ký tự',
    'register.full_name_min_error': 'Họ tên phải có ít nhất 2 ký tự',
    'register.email_invalid_error': 'Email không hợp lệ',
    'register.password_mismatch_error': 'Mật khẩu xác nhận không khớp',
    
    // Investment Utilities
    'utilities.title': 'Tiện ích đầu tư thông minh',
    'utilities.history': 'Lịch sử đầu tư: Xem chi tiết các khoản đầu tư trước đây, bao gồm thời gian, số tiền và lãi tích lũy.',
    'utilities.pdf_contract': 'Tải hợp đồng PDF: Tải nhanh hợp đồng đầu tư có chữ ký điện tử với đầy đủ thông tin pháp lý.',
    'utilities.withdrawal': 'Gửi yêu cầu rút vốn: Nộp yêu cầu rút vốn nhanh chóng, xử lý trong vòng 24h làm việc.',
    'utilities.notifications': 'Thông báo & cảnh báo: Nhận thông báo qua email khi đến hạn hợp đồng, thay đổi trạng thái, hoặc cập nhật hệ thống.',
    
    // Investment Guide
    'guide.title': 'Hướng dẫn đầu tư HHDcoin',
    'guide.step1': '1. Tạo tài khoản: Truy cập trang Đăng ký và điền thông tin cá nhân để bắt đầu hành trình đầu tư.',
    'guide.step2': '2. Nạp khoản đầu tư: Điền số tiền (VND), thời gian đầu tư (tháng) và hệ thống sẽ tính lãi suất %/tháng.',
    'guide.step3': '3. Thanh toán & nhận hợp đồng: Bạn có thể chuyển khoản ngân hàng hoặc gửi USDT/BTC. Sau khi xác nhận, hợp đồng PDF sẽ được tạo tự động.',
    'guide.step4': '4. Quản lý & theo dõi: Vào khu vực Quản lý tài khoản để xem lịch sử đầu tư, tải hợp đồng và gửi yêu cầu rút vốn.',
    'guide.step5': '5. Chatbot AI hỗ trợ: Dùng chatbot để được hỗ trợ bất cứ lúc nào, 24/7, cả tiếng Việt và tiếng Anh.',
    
    // Contact Page
    'contact.page_title': 'Liên hệ',
    'contact.page_subtitle': 'Liên hệ với đội ngũ chuyên gia HHDcoin để được hỗ trợ tốt nhất về đầu tư Bitcoin',
    'contact.info_title': 'Thông tin liên hệ',
    'contact.office_title': 'Văn phòng HHDcoin',
    'contact.headquarters': 'Trụ sở chính',
    'contact.full_address': 'Số 25, ngõ 155 đường Cầu Giấy, Phường Quan Hoa, Quận Cầu Giấy, Thành phố Hà Nội',
    'contact.working_hours': 'Giờ làm việc:',
    'contact.monday_friday': 'Thứ 2 - Thứ 6: 9:00 - 18:00',
    'contact.saturday': 'Thứ 7: 9:00 - 12:00',
    'contact.sunday': 'Chủ nhật: Nghỉ',
    'contact.support_24_7': 'Hỗ trợ 24/7:',
    'contact.ai_chatbot': 'Chatbot AI luôn sẵn sàng',
    'contact.email_support': 'Email support',
    'contact.zalo_consultation': 'Zalo consultation',
    'contact.phone_label': 'Điện thoại',
    'contact.address_label': 'Địa chỉ',
    'contact.facebook_label': 'Facebook',
    'contact.zalo_support': 'Zalo hỗ trợ HHDcoin',
    'contact.email': 'Email: haidh1975@gmail.com',
    'contact.phone': 'Tel: +84 888151975',
    'contact.address': 'Địa chỉ: Số 25, ngõ 155 đường Cầu Giấy, TP. Hà Nội',
    'contact.facebook': 'Facebook: Zalo hỗ trợ HHDcoin',
    
    // Features Section
    'features.title': 'Tại sao chọn HHDcoin?',
    'features.title_prefix': 'Tại sao chọn',
    'features.description': 'Những điểm khác biệt vượt trội giúp HHDcoin dẫn đầu thị trường đầu tư Bitcoin Việt Nam',
    'features.description_prefix': 'Những điểm khác biệt vượt trội giúp',
    'features.description_suffix': 'dẫn đầu thị trường đầu tư Bitcoin Việt Nam',
    'features.ai.title': 'AI Dự báo Thông minh',
    'features.ai.description': 'Công nghệ AI độc quyền phân tích 50+ chỉ số thị trường để đưa ra dự báo chính xác đến 89%',
    'features.speed.title': 'Cập nhật Siêu nhanh',
    'features.speed.description': 'Hệ thống real-time cập nhật giá Bitcoin và tin tức thị trường trong vòng 0.1 giây',
    'features.analysis.title': 'Phân tích Chuyên sâu',
    'features.analysis.description': 'Đội ngũ chuyên gia 10+ năm kinh nghiệm cung cấp phân tích kỹ thuật và cơ bản chi tiết',
    'features.free.title': 'Hoàn toàn Miễn phí',
    'features.free.description': 'Tất cả tính năng cơ bản hoàn toàn miễn phí, không phí ẩn, cam kết minh bạch',
    
    // Footer Section
    'footer.subtitle': 'Bitcoin Investment Platform',
    'footer.description': 'là nền tảng đầu tư Bitcoin hàng đầu Việt Nam, cung cấp công nghệ AI dự báo tiên tiến, phân tích thị trường chuyên sâu và dịch vụ tư vấn đầu tư chuyên nghiệp.',
    'footer.quick_links': 'Liên kết nhanh',
    'footer.support': 'Hỗ trợ',
    'footer.copyright': '© 2024 HHDcoin. Tất cả quyền được bảo lưu.',
    'footer.links.investment_guide': 'Hướng dẫn đầu tư',
    'footer.links.faq': 'FAQ',
    'footer.links.security': 'Bảo mật',
    'footer.links.terms': 'Điều khoản',
    'footer.links.policy': 'Chính sách',
    'footer.links.contact_support': 'Liên hệ hỗ trợ',
    'footer.links.privacy_policy': 'Chính sách bảo mật',
    'footer.links.terms_of_use': 'Điều khoản sử dụng',
    'footer.links.cookie_policy': 'Chính sách cookie',
    'footer.links.sitemap': 'Sitemap',
    
    // Investment Packages Page
    'packages.page.title': 'Gói Đầu Tư Bitcoin',
    'packages.page.description': 'Chọn gói đầu tư phù hợp với mục tiêu tài chính của bạn. Tất cả gói đều được hỗ trợ bởi AI và phân tích chuyên sâu.',
    'packages.calculator.title': 'Máy Tính Lợi Nhuận Đầu Tư',
    'packages.calculator.annual_profit': 'Lợi nhuận năm trung bình',
    'packages.calculator.ai_monitoring': 'Giám sát AI',
    'packages.calculator.prediction_accuracy': 'Độ chính xác dự đoán',
    'packages.loading': 'Đang tải gói đầu tư...',
    'packages.recommended': 'Đề xuất',
    'packages.profit_per_year': 'Lợi nhuận/năm',
    'packages.min_amount': 'Số tiền tối thiểu:',
    'packages.risk_level': 'Mức độ rủi ro:',
    'packages.risk.low': 'Thấp',
    'packages.risk.medium': 'Trung bình',
    'packages.risk.high': 'Cao',
    'packages.select_package': 'Chọn Gói Này',
    'packages.descriptions.basic': 'Gói đầu tư phù hợp cho người mới bắt đầu với rủi ro thấp',
    'packages.descriptions.intermediate': 'Gói đầu tư trung bình với lợi nhuận ổn định',
    'packages.descriptions.premium': 'Gói đầu tư cao cấp với tiềm năng lợi nhuận cao',
    'packages.descriptions.elite': 'Gói đầu tư VIP dành cho nhà đầu tư chuyên nghiệp',
    'packages.warning.title': 'Lưu Ý Quan Trọng',
    'packages.warning.content': 'Đầu tư cryptocurrency có rủi ro cao. Giá trị đầu tư có thể tăng hoặc giảm. Bạn nên cân nhắc kỹ lưỡng và chỉ đầu tư số tiền mà bạn có thể chấp nhận mất. Tham khảo ý kiến chuyên gia tài chính trước khi đưa ra quyết định đầu tư.',
    'packages.consultation.title': 'Cần Tư Vấn Thêm?',
    'packages.consultation.description': 'Đội ngũ chuyên gia của chúng tôi sẵn sàng hỗ trợ bạn chọn gói đầu tư phù hợp nhất.',
    'packages.consultation.button': 'Liên Hệ Tư Vấn',
    
    // Account Management
    'account.view_data': 'Xem dữ liệu đầu tư',
    
    // Common
    'common.loading': 'Đang tải...',
    'common.read_more': 'Đọc tiếp',
    'common.view_all': 'Xem tất cả',
    'common.success': 'Thành công',
    'common.error': 'Lỗi',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.edit': 'Chỉnh sửa',
    'common.delete': 'Xóa',
    'common.add': 'Thêm',
    'common.submit': 'Gửi',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.send': 'Gửi',
    'common.back': 'Quay lại',
    'common.next': 'Tiếp theo',
    'common.previous': 'Trước',
    'common.close': 'Đóng',
    'common.open': 'Mở',
    'common.select': 'Chọn',
    // Investment Purchase Page
    'purchase.login_required': 'Yêu cầu đăng nhập',
    'purchase.login_message': 'Vui lòng đăng nhập để tiếp tục đầu tư.',
    'purchase.back_to_packages': 'Quay lại gói đầu tư',
    'purchase.title': 'Đầu tư Bitcoin',
    'purchase.subtitle': 'Chọn gói đầu tư và bắt đầu hành trình đầu tư của bạn',
    'purchase.select_package': 'Chọn gói đầu tư',
    'purchase.recommended': 'Khuyến nghị',
    'purchase.min_investment': 'Đầu tư tối thiểu:',
    'purchase.profit_range': 'Lợi nhuận:',
    'purchase.investment_amount': 'Số tiền đầu tư',
    'purchase.amount_vnd': 'Số tiền (VNĐ)',
    'purchase.enter_amount': 'Nhập số tiền đầu tư',
    'purchase.minimum': 'Tối thiểu:',
    'purchase.summary': 'Tóm tắt đầu tư',
    'purchase.expected_profit': 'Lợi nhuận dự kiến:',
    'purchase.investment_amount_label': 'Số tiền đầu tư:',
    'purchase.package_benefits': 'Đặc quyền gói:',
    'purchase.pay_now': 'Thanh toán ngay',
    'purchase.processing': 'Đang xử lý...',
    'purchase.select_package_prompt': 'Vui lòng chọn gói đầu tư',
    'purchase.benefits_title': 'Lợi ích khi đầu tư',
    'purchase.benefit_security': 'Bảo mật an toàn với công nghệ blockchain',
    'purchase.benefit_ai': 'AI phân tích thị trường thời gian thực',
    'purchase.benefit_support': 'Hỗ trợ khách hàng 24/7',
    'purchase.error_payment': 'Lỗi thanh toán',
    'purchase.error_payment_desc': 'Không thể tạo thanh toán. Vui lòng thử lại.',
    'purchase.error_no_package': 'Chưa chọn gói',
    'purchase.error_no_package_desc': 'Vui lòng chọn gói đầu tư.',
    'purchase.error_invalid_amount': 'Số tiền không hợp lệ',
    'purchase.error_invalid_amount_desc': 'Vui lòng nhập số tiền đầu tư hợp lệ.',
    'purchase.error_amount_too_low': 'Số tiền quá thấp',
    'purchase.error_amount_too_low_desc': 'Số tiền đầu tư tối thiểu cho gói này là {amount}.',

    // Payment Success Page
    'payment_success.failed_title': 'Thanh toán không thành công',
    'payment_success.failed_message': 'Có vẻ như thanh toán của bạn gặp sự cố. Vui lòng thử lại.',
    'payment_success.try_again': 'Thử lại',
    'payment_success.go_dashboard': 'Về Dashboard',
    'payment_success.title': 'Thanh toán thành công! 🎉',
    'payment_success.congratulations': 'Chúc mừng bạn đã bắt đầu hành trình đầu tư Bitcoin cùng HHDcoin',
    'payment_success.payment_details': 'Chi tiết thanh toán',
    'payment_success.package': 'Gói đầu tư',
    'payment_success.amount': 'Số tiền',
    'payment_success.transaction_code': 'Mã giao dịch',
    'payment_success.status': 'Trạng thái',
    'payment_success.successful': 'Thành công',
    'payment_success.payment_time': 'Thời gian thanh toán',
    'payment_success.next_steps': 'Bước tiếp theo',
    'payment_success.next_steps_desc': 'Những gì sẽ xảy ra sau khi bạn thanh toán thành công',
    'payment_success.confirm_investment': 'Xác nhận đầu tư',
    'payment_success.confirm_investment_desc': 'Chúng tôi sẽ xử lý khoản đầu tư của bạn trong vòng 24 giờ',
    'payment_success.email_notification': 'Gửi thông báo email',
    'payment_success.email_notification_desc': 'Bạn sẽ nhận được email xác nhận và hướng dẫn chi tiết',
    'payment_success.track_investment': 'Theo dõi đầu tư',
    'payment_success.track_investment_desc': 'Truy cập dashboard để theo dõi hiệu suất đầu tư của bạn',
    'payment_success.view_other_packages': 'Xem thêm gói khác',
    'payment_success.questions': 'Có câu hỏi về khoản đầu tư của bạn?',
    'payment_success.contact_us': 'Liên hệ với chúng tôi',

    // Account Management Page
    'account.title': 'Quản lý tài khoản',
    'account.login_required': 'Yêu cầu đăng nhập',
    'account.login_message': 'Vui lòng đăng nhập để xem và quản lý đầu tư của bạn.',
    'account.hero_subtitle': 'Theo dõi và quản lý toàn bộ hoạt động đầu tư Bitcoin của bạn một cách dễ dàng',
    'account.my_investments': 'Quản lý đầu tư của tôi',
    'account.my_investments_desc': 'Theo dõi và quản lý toàn bộ hoạt động đầu tư Bitcoin của bạn',
    'account.new_investment': 'Đầu tư mới',
    'account.total_investment': 'Tổng đầu tư',
    'account.current_value': 'Giá trị hiện tại',
    'account.profit_loss': 'Lãi/Lỗ',
    'account.investments_list': 'Danh sách đầu tư ({count})',
    'account.loading_error': 'Lỗi tải dữ liệu đầu tư',
    'account.no_investments': 'Chưa có khoản đầu tư nào',
    'account.no_investments_desc': 'Bắt đầu hành trình đầu tư Bitcoin của bạn ngay hôm nay',
    'account.start_investing': 'Bắt đầu đầu tư',
    'account.bitcoin_code': 'Mã Bitcoin:',
    'account.status_active': 'Đang hoạt động',
    'account.status_completed': 'Hoàn thành',
    'account.status_cancelled': 'Đã hủy',
    'account.investment_date': 'Ngày đầu tư',
    'account.expected_profit': 'Lợi nhuận dự kiến',
    'account.investment_amount': 'Số tiền đầu tư',
    'account.current_value_label': 'Giá trị hiện tại',
    'account.profit_loss_label': 'Lãi/Lỗ',
    'account.view_details': 'Chi tiết',
    'account.actions_title': 'Thao tác tài khoản',
    'account.new_investment_action': 'Đầu tư mới',
    'account.withdrawal_request': 'Yêu cầu rút vốn',
    'account.account_settings': 'Cài đặt tài khoản',

    'common.confirm': 'Xác nhận',
    'common.yes': 'Có',
    'common.no': 'Không',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.account_management': 'Account Management',
    'nav.news': 'News',
    'nav.analysis': 'Analytics',
    'nav.community': 'Community',
    'nav.investment_management': 'Investment Management',
    'nav.investment_utilities': 'Investment Utilities',
    'nav.investment_guide': 'Investment Guide',
    'nav.contact': 'Contact',
    'nav.packages': 'Investment Packages',
    'nav.investment': 'Investment',
    
    // Hero Section
    'hero.title': 'Smart Bitcoin Investing with AI',
    'hero.title.highlight': 'Investment',
    'hero.title.suffix': 'with AI',
    'hero.description': 'Vietnam\'s leading Bitcoin investment platform with AI-driven forecasting, in-depth analysis, and real-time updates 24/7.',
    'hero.cta.invest': 'Start Investing',
    'hero.cta.demo': 'View AI Demo',
    'hero.feature.security': 'Absolute Security',
    'hero.feature.ai': 'Accurate AI Prediction',
    'hero.feature.realtime': '24/7 Updates',
    'hero.price.title': 'Current Bitcoin Price',
    'hero.ai.prediction': 'AI Prediction (7 days)',
    'hero.ai.confidence': 'Confidence:',
    
    // Investment Calculator
    'calc.title': 'Smart Investment Calculator',
    'calc.description': 'Calculate Bitcoin investment profits with AI forecasting and automatic risk analysis',
    'calc.form.title': 'Investment Calculation',
    'calc.form.amount': 'Investment Amount (VND)',
    'calc.form.duration': 'Investment Duration',
    'calc.form.package': 'Investment Package',
    'calc.risk.level': 'Risk Level',
    'calc.results.title': 'Forecast Results',
    'calc.results.investment': 'Total Investment',
    'calc.results.profit': 'Estimated Profit',
    'calc.results.total': 'Total Return',
    'calc.ai.trend': 'Strong Upward Trend',
    'calc.ai.confidence': 'Confidence: 89%',
    'calc.cta': 'Start Investing Now',
    
    // Investment Section
    'investment.title': 'Smart Bitcoin Investment',
    'investment.description': 'Explore investment packages and track the performance of our investor community',
    'investment.tabs.packages': 'Investment Packages',
    'investment.tabs.investors': 'Investors',
    
    // Investment Packages
    'packages.title': 'HHDcoin Investment Packages',
    'packages.description': 'Choose the investment package that suits your financial goals',
    'packages.popular': 'MOST POPULAR',
    'packages.profit': 'Profit/year',
    'packages.select': 'Select This Package',
    
    // Contact
    'contact.title': 'Contact & Support',
    'contact.description': 'HHDcoin expert team is always ready to support you 24/7',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    
    // Investors
    'investors.title': 'Investor Information Table',
    'investors.description': 'Track investment performance and achievements of investors on the HHDcoin platform',
    'investors.stats.total': 'Total Investors',
    'investors.stats.investment': 'Total Investment',
    'investors.stats.profit': 'Total Profit',
    'investors.table.name': 'Full Name',
    'investors.table.email': 'Email',
    'investors.table.phone': 'Phone',
    'investors.table.amount': 'Investment Amount',
    'investors.table.time': 'Time',
    'investors.table.bitcoin': 'Bitcoin Code',
    'investors.table.currentValue': 'Current Value',
    'investors.table.profit': 'Profit/Loss',
    'investors.table.percentage': 'Percentage',
    'investors.table.status': 'Status',
    'investors.status.active': 'Active',
    'investors.status.inactive': 'Inactive',
    
    // News Section
    'news.title': 'Latest News',
    'news.bitcoin_title': 'Bitcoin Price Surges',
    'news.ai_title': 'AI Predicts Minor Correction',
    'news.mobile_title': 'HHDcoin Launches Mobile App',
    'news.bitcoin_surge': 'Bitcoin Price Surges: BTC price surpassed the $125,000 mark for the first time in 2025 due to strong institutional buying.',
    'news.ai_prediction': 'AI Predicts Minor Correction: The AI model indicates a 63% probability of a price correction over the next 3 days.',
    'news.mobile_app': 'HHDcoin Launches Mobile App: The AI-integrated Bitcoin investment app is now available on iOS and Android.',
    
    // Analytics Page
    'analytics.title': 'Analytics',
    'analytics.investment_chart': 'Investment Chart: AI will analyze growth trends, investment recommendations, and risks based on the latest data.',
    'analytics.market_share': 'Market Share Chart: Compare the investment percentage between different coins and your total portfolio.',
    'analytics.interest_rate': 'Interest Rate Analysis: Automatically evaluate performance based on a monthly interest rate percentage.',
    
    // Community Page
    'community.join_title': 'Join the HHDcoin Community',
    'community.form.full_name': 'Full Name',
    'community.form.email': 'Email',
    'community.form.phone': 'Phone Number',
    'community.form.zalo': 'Contact via Zalo',
    'community.form.submit': 'Submit',
    'community.title': 'HHDcoin Investment Community',
    'community.description': 'Connect with the Bitcoin investor community, share experiences and learn from experts',
    'community.stats.total_members': 'Total Members',
    'community.stats.active_today': 'Active Today',
    'community.stats.total_discussions': 'Total Discussions',
    'community.add_member': 'Add Member',
    'community.add_member_dialog_title': 'Add New Member',
    'community.search_placeholder': 'Search members...',
    'community.filter_experience': 'Filter by experience',
    'community.filter_member_level': 'Filter by level',
    'community.clear_filters': 'Clear filters',
    'community.experience.beginner': 'Beginner',
    'community.experience.intermediate': 'Intermediate',
    'community.experience.advanced': 'Advanced',
    'community.experience.expert': 'Expert',
    'community.member_level.bronze': 'Bronze',
    'community.member_level.silver': 'Silver',
    'community.member_level.gold': 'Gold',
    'community.member_level.diamond': 'Diamond',
    'community.form.job_title': 'Job Title',
    'community.form.company': 'Company',
    'community.form.location': 'Location',
    'community.form.experience_level': 'Experience Level',
    'community.form.member_level': 'Member Level',
    'community.form.interests': 'Interests',
    'community.form.bio': 'Bio',
    'community.form.facebook_profile': 'Facebook Profile',
    'community.form.is_public_profile': 'Public Profile',
    'community.form.newsletter': 'Newsletter',
    'community.success.member_added': 'New member has been added to the community!',
    'community.success.member_deleted': 'Member has been removed from the community',
    'community.error.add_member': 'An error occurred while adding new member',
    'community.error.delete_member': 'An error occurred while deleting member',
    'community.button.cancel': 'Cancel',
    'community.button.adding': 'Adding...',
    'community.button.add_member': 'Add Member',
    'community.button.contact_zalo': 'Contact Zalo',
    'community.button.edit': 'Edit',
    'community.button.delete': 'Delete',
    'community.button.message': 'Message',
    'community.loading': 'Loading community...',
    'community.no_members': 'No members yet',
    
    // Community - Additional missing translations
    'community.form.occupation': 'Occupation',
    'community.form.bio_label': 'Bio',
    'community.social_media_title': 'Social Media Information',
    'community.facebook_url': 'Facebook URL',
    'community.zalo_phone': 'Zalo (Phone Number)',
    'community.placeholder.search_members': 'Search members...',
    'community.placeholder.experience_level': 'Experience Level',
    'community.placeholder.member_level': 'Member Level',
    'community.placeholder.all': 'All',
    'community.loading_members': 'Loading member list...',
    'community.member.joined': 'Joined:',
    'community.member.interests': 'Interests:',
    'community.member.points': 'Points: ',
    'community.member.active': 'Active',
    'community.member.inactive': 'Inactive',
    'community.no_members_found': 'No members found',
    'community.no_members_hint': 'Try changing filters or search keywords',
    'community.confirm_delete': 'Are you sure you want to remove member {{name}} from the community?',
    'community.placeholder.full_name': 'John Doe',
    'community.placeholder.email': 'email@example.com',
    'community.placeholder.phone': '0987654321',
    'community.placeholder.location': 'Hanoi',
    'community.placeholder.occupation': 'Software Engineer',
    'community.placeholder.bio': 'Share your investment experience and goals...',
    'community.placeholder.facebook': 'https://facebook.com/username',
    'community.placeholder.zalo': '0987654321',
    
    // Analysis Page
    'analysis.title': 'AI & Market Analysis',
    'analysis.description': 'Comprehensive AI analysis to make smart and effective investment decisions',
    'analysis.features_title': 'Analysis Features',
    'analysis.investment_chart': 'Investment Chart',
    'analysis.market_share': 'Market Share Chart',
    'analysis.interest_rate_analysis': 'Interest Rate Analysis',
    'analysis.ai_insights': 'AI Insights & Analysis',
    'analysis.ai_description': 'Smart market analysis with GPT-5 AI technology',
    'analysis.refresh': 'Refresh',
    'analysis.market_analysis': 'AI Market Analysis',
    'analysis.trading_recommendations': 'Trading Recommendations',
    'analysis.sentiment_analysis': 'News Sentiment Analysis',
    'analysis.analyzing': 'Analyzing...',
    'analysis.confidence': 'Confidence:',
    'analysis.risk_level': 'Risk Level:',
    'analysis.price_targets': 'Price Targets',
    'analysis.short_term': 'Short Term',
    'analysis.medium_term': 'Medium Term',
    'analysis.key_factors': 'Key Factors:',
    'analysis.ai_recommendation': 'AI Recommendation',
    'analysis.analysis_type': 'Analysis Type:',
    'analysis.updated': 'Updated:',
    'analysis.login_required': 'Please login to view trading recommendations',
    'analysis.creating_recommendations': 'Creating recommendations...',
    'analysis.risk_profile': 'Risk Profile:',
    'analysis.conservative': 'Conservative',
    'analysis.moderate': 'Moderate',
    'analysis.aggressive': 'Aggressive',
    'analysis.buy': 'BUY',
    'analysis.sell': 'SELL',
    'analysis.hold': 'HOLD',
    'analysis.reasoning': 'Reasoning:',
    'analysis.timeframe': 'Timeframe:',
    'analysis.bitcoin_price': 'Bitcoin Price:',
    'analysis.change_24h': '24h Change:',
    'analysis.risk_assessment': 'Risk Assessment',
    'analysis.sentiment_login_required': 'Please login to use sentiment analysis',
    'analysis.news_input_label': 'Enter Bitcoin news or articles:',
    'analysis.news_placeholder': 'Paste news content, articles or Bitcoin comments to analyze market sentiment...',
    'analysis.analyze_sentiment': 'Analyze Sentiment',
    'analysis.analyzing_sentiment': 'Analyzing...',
    'analysis.sentiment_results': 'Analysis Results:',
    'analysis.sentiment_summary': 'Summary:',
    'analysis.analyzed_at': 'Analyzed at:',
    'analysis.error_no_data': 'Unable to load analysis data',
    'analysis.error_no_recommendations': 'Unable to load trading recommendations',
    'analysis.toast.error_title': 'Error',
    'analysis.toast.no_text': 'Please enter text to analyze sentiment',
    'analysis.toast.analysis_complete': 'Analysis complete',
    'analysis.toast.analysis_error': 'Analysis error',
    'analysis.toast.analysis_error_desc': 'Cannot analyze sentiment. Please try again.',
    
    // Dashboard Page
    'dashboard.welcome': 'Welcome, {{name}}!',
    'dashboard.subtitle': 'Manage your account and track your Bitcoin investments',
    'dashboard.admin': 'Admin',
    'dashboard.member': 'Member',
    'dashboard.logout': 'Logout',
    'dashboard.account_info': 'Account Information',
    'dashboard.email_not_updated': 'Email not updated',
    'dashboard.current_bitcoin_price': 'Current Bitcoin Price',
    'dashboard.portfolio_value': 'Portfolio Value',
    'dashboard.no_investments': 'No investments yet',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.frequent_features': 'Frequently used features',
    'dashboard.view_packages': 'View Investment Packages',
    'dashboard.market_analysis': 'Market Analysis',
    'dashboard.community': 'Community',
    'dashboard.admin_panel': 'System Management',
    'dashboard.account_details': 'Account Details',
    'dashboard.personal_info': 'Personal information and settings',
    'dashboard.account': 'Account:',
    'dashboard.full_name': 'Full Name:',
    'dashboard.email': 'Email:',
    'dashboard.role': 'Role:',
    'dashboard.status': 'Status:',
    'dashboard.administrator': 'Administrator',
    'dashboard.member_role': 'Member',
    'dashboard.active': 'Active',
    'dashboard.account_settings': 'Account Settings',
    'dashboard.not_updated': 'Not updated',
    
    // Login Page
    'login.title': 'Login to HHDcoin',
    'login.subtitle': 'Access your Bitcoin investment account',
    'login.username_label': 'Username',
    'login.username_placeholder': 'Enter your username',
    'login.password_label': 'Password',
    'login.password_placeholder': 'Enter your password',
    'login.login_button': 'Login',
    'login.logging_in': 'Logging in...',
    'login.or': 'Or',
    'login.no_account': "Don't have an account?",
    'login.register_now': 'Register now',
    'login.demo_accounts': 'Demo accounts:',
    'login.admin_demo': 'Admin:',
    'login.member_demo': 'Member:',
    'login.success_title': 'Login successful!',
    'login.success_description': 'Welcome back to HHDcoin.',
    'login.username_min_error': 'Username must be at least 3 characters',
    'login.password_min_error': 'Password must be at least 6 characters',
    
    // Register Page
    'register.title': 'Register to HHDcoin',
    'register.subtitle': 'Create an account to start Bitcoin investing',
    'register.username_label': 'Username',
    'register.username_placeholder': 'Enter desired username',
    'register.password_label': 'Password',
    'register.password_placeholder': 'Enter password',
    'register.confirm_password_label': 'Confirm Password',
    'register.confirm_password_placeholder': 'Re-enter password',
    'register.full_name_label': 'Full Name',
    'register.full_name_placeholder': 'Enter full name',
    'register.email_label': 'Email (optional)',
    'register.email_placeholder': 'Enter email address',
    'register.register_button': 'Register',
    'register.registering': 'Registering...',
    'register.or': 'Or',
    'register.have_account': 'Already have an account?',
    'register.login_now': 'Login now',
    'register.success_title': 'Registration successful!',
    'register.success_description': 'Welcome to HHDcoin.',
    'register.username_min_error': 'Username must be at least 3 characters',
    'register.password_min_error': 'Password must be at least 6 characters',
    'register.full_name_min_error': 'Full name must be at least 2 characters',
    'register.email_invalid_error': 'Invalid email',
    'register.password_mismatch_error': 'Password confirmation does not match',
    
    // Investment Utilities
    'utilities.title': 'Smart Investment Utilities',
    'utilities.history': 'Investment History: View detailed past investments, including time, amount, and accumulated profit.',
    'utilities.pdf_contract': 'Download PDF Contract: Quickly download investment contracts with electronic signatures and full legal information.',
    'utilities.withdrawal': 'Submit Withdrawal Request: Submit your withdrawal request quickly; it will be processed within 24 working hours.',
    'utilities.notifications': 'Notifications & Alerts: Receive email notifications when a contract expires, a status changes, or a system update occurs.',
    
    // Investment Guide
    'guide.title': 'HHDcoin Investment Guide',
    'guide.step1': '1. Create an Account: Go to the Register page and fill in your personal information to start your investment journey.',
    'guide.step2': '2. Deposit Funds: Enter the amount (VND) and investment duration (months); the system will calculate the monthly interest rate.',
    'guide.step3': '3. Make Payment & Receive Contract: You can transfer via bank or send USDT/BTC. After confirmation, a PDF contract will be automatically generated.',
    'guide.step4': '4. Manage & Track: Access the Account Management area to view your investment history, download contracts, and submit withdrawal requests.',
    'guide.step5': '5. AI Chatbot Support: Use our chatbot for 24/7 assistance in both Vietnamese and English.',
    
    // Contact Page
    'contact.page_title': 'Contact',
    'contact.page_subtitle': 'Contact the HHDcoin team of experts for the best support on Bitcoin investment',
    'contact.info_title': 'Contact Information',
    'contact.office_title': 'HHDcoin Office',
    'contact.headquarters': 'Headquarters',
    'contact.full_address': '25, lane 155 Cau Giay street, Quan Hoa Ward, Cau Giay District, Hanoi City',
    'contact.working_hours': 'Working Hours:',
    'contact.monday_friday': 'Monday - Friday: 9:00 AM - 6:00 PM',
    'contact.saturday': 'Saturday: 9:00 AM - 12:00 PM',
    'contact.sunday': 'Sunday: Closed',
    'contact.support_24_7': '24/7 Support:',
    'contact.ai_chatbot': 'AI Chatbot always ready',
    'contact.email_support': 'Email support',
    'contact.zalo_consultation': 'Zalo consultation',
    'contact.phone_label': 'Phone',
    'contact.address_label': 'Address',
    'contact.facebook_label': 'Facebook',
    'contact.zalo_support': 'HHDcoin Zalo Support',
    'contact.email': 'Email: haidh1975@gmail.com',
    'contact.phone': 'Tel: +84 888151975',
    'contact.address': 'Address: 25, lane 155 Cau Giay street, Hanoi city, Vietnam',
    'contact.facebook': 'Facebook: HHDcoin Zalo Support',
    
    // Features Section
    'features.title': 'Why choose HHDcoin?',
    'features.title_prefix': 'Why choose',
    'features.description': 'The superior advantages that help HHDcoin lead the Vietnamese Bitcoin investment market',
    'features.description_prefix': 'The superior advantages that help',
    'features.description_suffix': 'lead the Vietnamese Bitcoin investment market',
    'features.ai.title': 'Smart AI Prediction',
    'features.ai.description': 'Proprietary AI technology analyzes 50+ market indicators to deliver predictions with up to 89% accuracy',
    'features.speed.title': 'Lightning Fast Updates',
    'features.speed.description': 'Real-time system updates Bitcoin prices and market news within 0.1 seconds',
    'features.analysis.title': 'In-depth Analysis',
    'features.analysis.description': 'Expert team with 10+ years of experience provides detailed technical and fundamental analysis',
    'features.free.title': 'Completely Free',
    'features.free.description': 'All basic features are completely free, no hidden fees, with transparent commitment',
    
    // Footer Section
    'footer.subtitle': 'Bitcoin Investment Platform',
    'footer.description': 'is Vietnam\'s leading Bitcoin investment platform, providing advanced AI prediction technology, in-depth market analysis, and professional investment consulting services.',
    'footer.quick_links': 'Quick Links',
    'footer.support': 'Support',
    'footer.copyright': '© 2024 HHDcoin. All rights reserved.',
    'footer.links.investment_guide': 'Investment Guide',
    'footer.links.faq': 'FAQ',
    'footer.links.security': 'Security',
    'footer.links.terms': 'Terms',
    'footer.links.policy': 'Policy',
    'footer.links.contact_support': 'Contact Support',
    'footer.links.privacy_policy': 'Privacy Policy',
    'footer.links.terms_of_use': 'Terms of Use',
    'footer.links.cookie_policy': 'Cookie Policy',
    'footer.links.sitemap': 'Sitemap',
    
    // Investment Packages Page
    'packages.page.title': 'Bitcoin Investment Packages',
    'packages.page.description': 'Choose the investment package that suits your financial goals. All packages are supported by AI and in-depth analysis.',
    'packages.calculator.title': 'Investment Profit Calculator',
    'packages.calculator.annual_profit': 'Average annual profit',
    'packages.calculator.ai_monitoring': 'AI Monitoring',
    'packages.calculator.prediction_accuracy': 'Prediction accuracy',
    'packages.loading': 'Loading investment packages...',
    'packages.recommended': 'Recommended',
    'packages.profit_per_year': 'Profit/year',
    'packages.min_amount': 'Minimum amount:',
    'packages.risk_level': 'Risk level:',
    'packages.risk.low': 'Low',
    'packages.risk.medium': 'Medium',
    'packages.risk.high': 'High',
    'packages.select_package': 'Select This Package',
    'packages.descriptions.basic': 'Investment package suitable for beginners with low risk',
    'packages.descriptions.intermediate': 'Medium investment package with stable profits',
    'packages.descriptions.premium': 'Premium investment package with high profit potential',
    'packages.descriptions.elite': 'VIP investment package for professional investors',
    'packages.warning.title': 'Important Notice',
    'packages.warning.content': 'Cryptocurrency investment involves high risk. Investment value may increase or decrease. You should consider carefully and only invest money that you can afford to lose. Consult financial experts before making investment decisions.',
    'packages.consultation.title': 'Need More Consultation?',
    'packages.consultation.description': 'Our team of experts is ready to help you choose the most suitable investment package.',
    'packages.consultation.button': 'Contact for Consultation',
    
    // Account Management
    'account.title': 'View Investment Data',
    
    // Common
    'common.loading': 'Loading...',
    'common.read_more': 'Read More',
    'common.view_all': 'View All',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.send': 'Send',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.select': 'Select',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('vi');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'vi' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations['vi']] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(new RegExp(`{${paramKey}}`, 'g'), String(value));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}