import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  vi: {
    // Navigation
    'nav.home': 'Trang chủ',
    'nav.account_management': 'Quản lý tài khoản',
    'nav.news': 'Tin tức',
    'nav.analysis': 'Phân tích',
    'nav.community': 'Cộng đồng',
    'nav.investment_management': 'Quản lý đầu tư',
    'nav.investment_utilities': 'Tiện ích đầu tư',
    'nav.investment_guide': 'Hướng dẫn đầu tư',
    'nav.contact': 'Liên hệ',
    'nav.packages': 'Gói đầu tư',
    'nav.investment': 'Đầu tư',

    // Investment Calculator - CRITICAL FIXES
    'calc.title': 'Máy tính đầu tư thông minh',
    'calc.description': 'Tính toán lợi nhuận đầu tư Bitcoin với AI dự báo và phân tích rủi ro tự động',
    'calc.form.title': 'Tính toán đầu tư',
    'calc.form.amount': 'Số tiền đầu tư (VNĐ)',
    'calc.form.amount_placeholder': 'Nhập số tiền...',
    'calc.form.duration': 'Thời gian đầu tư',
    'calc.form.duration.months': 'tháng',
    'calc.form.duration.6': '6 tháng',
    'calc.form.duration.12': '12 tháng',
    'calc.form.duration.18': '18 tháng',
    'calc.form.duration.24': '24 tháng',
    'calc.form.package': 'Gói đầu tư',
    'calc.package.basic': 'Cơ bản',
    'calc.package.premium': 'Cao cấp',
    'calc.package.vip': 'VIP',
    'calc.risk.level': 'Mức độ rủi ro',
    'calc.risk.low': 'Thấp',
    'calc.risk.medium': 'Trung bình',
    'calc.risk.high': 'Cao',
    'calc.results.title': 'Kết quả dự báo',
    'calc.results.investment': 'Tổng đầu tư',
    'calc.results.profit': 'Lợi nhuận ước tính',
    'calc.results.total': 'Tổng nhận về',
    'calc.ai.prediction_title': 'Dự báo AI',
    'calc.ai.trend': 'Xu hướng tăng mạnh',
    'calc.ai.confidence': 'Độ tin cậy: 89%',
    'calc.ai.scenario': 'Kịch bản tăng mạnh',
    'calc.ai.market_signals': 'Tín hiệu thị trường',
    'calc.ai.positive_signals': 'Tích cực',
    'calc.ai.neutral_signals': 'Trung tính',
    'calc.ai.negative_signals': 'Tiêu cực',
    'calc.disclaimer.title': 'Lưu ý quan trọng',
    'calc.disclaimer.text': 'Kết quả tính toán chỉ mang tính tham khảo. Đầu tư có rủi ro, giá trị có thể tăng hoặc giảm.',
    'calc.cta': 'Bắt đầu đầu tư ngay',

    // Contact Support - CRITICAL FIXES
    'contact.title': 'Liên hệ & Hỗ trợ',
    'contact.description': 'Đội ngũ chuyên gia HHDcoin luôn sẵn sàng hỗ trợ bạn 24/7',
    'contact.live_support': 'Hỗ trợ trực tuyến',
    'contact.response_time': 'Phản hồi trong vòng 2 giờ',
    'contact.support_247': 'Hỗ trợ 24/7',
    'contact.ai_assistant': 'AI Assistant luôn sẵn sàng',
    'contact.support_options.live_chat': 'Live Chat',
    'contact.support_options.video_call': 'Video Call',
    'contact.support_options.faq': 'FAQ',
    'contact.support_options.guide': 'Hướng dẫn',
    'contact.support_options.live_chat_subtitle': 'Trực tuyến',
    'contact.support_options.video_call_subtitle': 'Đặt lịch',
    'contact.support_options.faq_subtitle': 'Câu hỏi thường gặp',
    'contact.support_options.guide_subtitle': 'Tài liệu chi tiết',
    'contact.info.title': 'Thông tin liên hệ',
    'contact.form.name': 'Họ và tên',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Số điện thoại',
    'contact.form.subject': 'Chủ đề',
    'contact.form.message': 'Nội dung',
    'contact.form.send': 'Gửi tin nhắn',
    'contact.form.sending': 'Đang gửi...',
    'contact.privacy_policy': 'Tôi đồng ý với chính sách bảo mật',
    'contact.privacy_required': 'Vui lòng đồng ý với chính sách bảo mật',
    'contact.all_fields_required': 'Vui lòng điền đầy đủ thông tin bắt buộc',
    'contact.send_success': 'Tin nhắn đã được gửi thành công!',
    'contact.send_error': 'Có lỗi xảy ra khi gửi tin nhắn',

    // News Analysis - CRITICAL FIXES
    'news.title': 'Tin tức & Phân tích',
    'news.description': 'Cập nhật mới nhất từ thị trường Bitcoin',
    'news.featured_article_title': '🚀 Bitcoin chính thức vượt mốc $150K: Kỷ lục lịch sử mới!',
    'news.featured_article_excerpt': 'Lần đầu tiên trong lịch sử, Bitcoin đã phá vỡ ngưỡng tâm lý $150,000, đánh dấu cột mốc quan trọng cho thị trường crypto. AI dự báo của HHDcoin đã chính xác dự đoán sự kiện này với độ tin cậy 94%. Các chuyên gia nhận định đây là bước ngoặt quan trọng trong việc Bitcoin trở thành tài sản dự trữ toàn cầu...',
    'news.featured_category': 'Phân tích chuyên sâu',
    'news.time_ago': 'trước',
    'news.hours': 'giờ',
    'news.minutes': 'phút',
    'news.status.hot': 'Nóng hổi',
    'news.status.government': 'Chính phủ',
    'news.status.technology': 'Công nghệ',
    'news.status.country': 'Quốc gia',
    'news.read_more': 'Đọc thêm',
    'news.view_all_news': 'Xem tất cả tin tức',
    'news.latest_updates': 'Cập nhật mới nhất từ thị trường Bitcoin',
    'news.breaking_news': 'Tin tức khẩn cấp',
    'news.market_news': 'Tin thị trường',
    
    // News Items - NEW TRANSLATIONS
    'news.item1.title': '💰 BlackRock ETF đạt $100 tỷ AUM sau khi Bitcoin vượt $150K',
    'news.item2.title': '🏛️ El Salvador công bố mua thêm 1000 BTC tại mức $150K',
    'news.item3.title': '⚡ Lightning Network xử lý 10M giao dịch/ngày',
    'news.item4.title': '🌏 Nhật Bản xem xét Bitcoin làm tài sản dự trữ',
    
    // Community Discussion Posts - NEW TRANSLATIONS
    'community.post1.user': 'Nguyễn Hoàng',
    'community.post1.title': 'Có nên DCA Bitcoin trong tình hình hiện tại?',
    'community.post1.preview': 'Với việc giá Bitcoin đang dao động quanh mức $43K, mọi người nghĩ sao về chiến lược DCA...',
    'community.post2.user': 'HHDcoin AI Assistant',
    'community.post2.title': 'Báo cáo phân tích thị trường tuần này',
    'community.post2.preview': 'AI phân tích cho thấy Bitcoin có 78% khả năng tăng giá trong 7 ngày tới dựa trên...',
    'community.post3.user': 'Lê Thành',
    'community.post3.title': 'Phân tích kỹ thuật: Mô hình cờ bull đang hình thành',
    'community.post3.preview': 'Quan sát biểu đồ 4H của Bitcoin, tôi thấy mô hình bull flag rất rõ ràng. Target ngắn hạn...',
    'community.reply_button.default': 'Trả lời',
    'community.reply_button.bot': 'Xem báo cáo đầy đủ',

    // Market Analysis - CRITICAL FIXES
    'market.title': 'Phân tích thị trường',
    'market.description': 'Bitcoin vượt $150K - Phân tích kỹ thuật và xu hướng thị trường trong bull run lịch sử',
    'market.bitcoin_surges': '🚀 Bitcoin phá vỡ mọi kỷ lục - Đạt $152,500 ATH!',
    'market.realtime_updates': 'Biểu đồ real-time từ CoinGecko & Binance - Cập nhật mỗi 30 giây',
    'market.24h_high': 'Cao nhất 24h',
    'market.24h_low': 'Thấp nhất 24h',
    'market.24h_volume': 'Khối lượng 24h',
    'market.24h_change': 'Thay đổi 24h',
    'market.chart_title': 'Biểu đồ giá Bitcoin',
    'market.technical_indicators': 'Chỉ báo kỹ thuật',
    'market.rsi': 'RSI (14)',
    'market.macd': 'MACD',
    'market.ma_50_200': 'MA 50/200',
    'market.volume': 'Volume',
    'market.super_bull': 'Super Bull',
    'market.insights_title': 'Insights từ AI',
    'market.key_insights': 'Điểm chính',
    'market.institutional_adoption': 'Sự chấp nhận từ tổ chức tăng mạnh 340%',
    'market.technical_breakout': 'Đột phá kỹ thuật vượt resistance $148K',
    'market.bullish_momentum': 'Momentum tăng giá cực mạnh với RSI > 70',
    'market.volume_surge': 'Khối lượng giao dịch tăng 185% so với trung bình',
    'market.ai_prediction': 'Dự báo AI cho 7 ngày tới',
    'market.bull_run_continues': 'Bull run tiếp tục với xác suất 91%',
    'market.target_range': 'Mục tiêu: $165K - $180K',
    'market.support_level': 'Hỗ trợ mạnh tại $145K',
    'market.view_detailed_analysis': 'Xem phân tích chi tiết',

    // Community Section - CRITICAL FIXES
    'community.title': 'Cộng đồng HHDcoin',
    'community.description': 'Kết nối với hàng nghìn nhà đầu tư Bitcoin, chia sẻ kinh nghiệm và học hỏi từ các chuyên gia',
    'community.community_stats': 'Thống kê cộng đồng',
    'community.stats.members': 'Thành viên',
    'community.stats.messages_today': 'Tin nhắn hôm nay',
    'community.stats.experts': 'Chuyên gia',
    'community.stats.countries': 'Quốc gia',
    'community.discussions.title': 'Thảo luận nổi bật',
    'community.view_all_discussions': 'Xem tất cả thảo luận',
    'community.join_community': 'Tham gia cộng đồng',
    'community.member_levels.vip': 'VIP Member',
    'community.member_levels.bot': 'BOT',
    'community.member_levels.expert': 'Expert Trader',
    'community.likes': 'lượt thích',
    'community.replies': 'phản hồi',
    'community.login_required': 'Vui lòng đăng nhập để tham gia thảo luận',

    // Investment Packages - CRITICAL FIXES
    'packages.loading_message': 'Đang tải gói đầu tư...',
    'packages.popular': 'PHỔ BIẾN NHẤT',
    'packages.profit': 'Lợi nhuận/năm',
    'packages.features': 'Tính năng',
    'packages.contact_for_investment': 'Liên hệ để được tư vấn đầu tư',
    'packages.select': 'Chọn gói này',

    // Pages - CRITICAL FIXES
    'pages.news.title': 'Tin Tức & Phân Tích',
    'pages.news.subtitle': 'Cập nhật tin tức mới nhất về Bitcoin và thị trường cryptocurrency',
    'pages.investment_guide.title': 'Hướng dẫn đầu tư HHDcoin',
    'pages.investment_guide.step_by_step': 'Hướng dẫn chi tiết từng bước để bắt đầu hành trình đầu tư Bitcoin thông minh với AI và các tiện ích đầu tư',
    'pages.investment_guide.utilities_title': 'Tiện ích đầu tư thông minh',

    // Investment Guide - CRITICAL FIXES
    'guide.five_steps_title': '5 Bước Đầu Tư Với HHDcoin',
    'guide.step1_title': 'Bước 1: Tạo tài khoản',
    'guide.step2_title': 'Bước 2: Nạp khoản đầu tư',
    'guide.step3_title': 'Bước 3: Thanh toán & nhận hợp đồng',
    'guide.step4_title': 'Bước 4: Quản lý & theo dõi',
    'guide.step5_title': 'Bước 5: Chatbot AI hỗ trợ',
    'guide.view_history': 'Xem lịch sử',
    'guide.download_contract': 'Tải hợp đồng',
    'guide.send_request': 'Gửi yêu cầu',
    'guide.manage_notifications': 'Quản lý thông báo',
    'guide.ready_to_start': 'Sẵn sàng bắt đầu đầu tư?',
    'guide.follow_steps_description': 'Theo dõi 5 bước trên để bắt đầu hành trình đầu tư Bitcoin thông minh cùng HHDcoin',
    'guide.start_now': 'Bắt đầu ngay',
    'guide.contact_support': 'Liên hệ hỗ trợ',
    'guide.demo_interface': 'Demo Interface',
    'guide.latest_investment': 'Đầu tư gần nhất',
    'guide.contract': 'Hợp đồng',
    'guide.download_pdf': 'Tải PDF',
    'guide.status': 'Trạng thái',
    'guide.active': 'Hoạt động',

    // My Investments - CRITICAL FIXES
    'my_investments.title': 'Quản Lý Đầu Tư',
    'my_investments.login_required_title': 'Yêu cầu đăng nhập',
    'my_investments.login_required_message': 'Bạn cần đăng nhập để xem thông tin đầu tư của mình.',
    'my_investments.login_button': 'Đăng nhập ngay',
    'my_investments.no_investments_title': 'Chưa có khoản đầu tư nào',
    'my_investments.no_investments_message': 'Bạn chưa có khoản đầu tư nào. Hãy bắt đầu đầu tư ngay hôm nay!',
    'my_investments.start_investing': 'Bắt đầu đầu tư',
    'my_investments.portfolio_overview': 'Quản lý và theo dõi các khoản đầu tư Bitcoin của bạn',
    'my_investments.total_invested': 'Tổng đầu tư',
    'my_investments.current_value': 'Giá trị hiện tại',
    'my_investments.total_profit': 'Tổng lợi nhuận',
    'my_investments.investment_details': 'Chi tiết đầu tư',
    'my_investments.investment_amount': 'Số tiền đầu tư',
    'my_investments.profit_loss': 'Lãi/Lỗ',
    'my_investments.profit_loss_percentage': 'Phần trăm lãi/lỗ',
    'my_investments.start_date': 'Ngày bắt đầu',
    'my_investments.end_date': 'Ngày kết thúc',
    'my_investments.bitcoin_code': 'Mã Bitcoin',
    'my_investments.status.active': 'Đang hoạt động',
    'my_investments.status.completed': 'Hoàn thành',
    'my_investments.status.cancelled': 'Đã hủy',
    'my_investments.package_name': 'Gói đầu tư',
    'my_investments.view_details': 'Xem chi tiết',
    'my_investments.loading': 'Đang tải dữ liệu đầu tư...',
    'my_investments.error': 'Có lỗi xảy ra khi tải dữ liệu',
    'my_investments.details_button': 'Chi tiết',
    'my_investments.no_investments_description': 'Bắt đầu hành trình đầu tư Bitcoin của bạn ngay hôm nay',
    'my_investments.start_investing_button': 'Bắt đầu đầu tư',
    'my_investments.investment_date': 'Ngày đầu tư',
    'my_investments.expected_profit': 'Lợi nhuận dự kiến',
    'my_investments.loading_error': 'Lỗi tải dữ liệu đầu tư',

    // Analysis page
    'analysis.title': 'Phân Tích Thị Trường',
    'analysis.description': 'Phân tích chuyên sâu với AI — xu hướng, khuyến nghị và đánh giá rủi ro theo thời gian thực',
    'analysis.features_title': 'Công Cụ Phân Tích',
    'analysis.investment_chart': 'Biểu đồ đầu tư',
    'analytics.investment_chart': 'Theo dõi hiệu suất danh mục theo thời gian thực',
    'analysis.market_share': 'Thị phần',
    'analytics.market_share': 'Phân bổ vốn hóa các đồng tiền số hàng đầu',
    'analysis.interest_rate_analysis': 'Phân tích lãi suất',
    'analytics.interest_rate': 'Tác động lãi suất đến thị trường crypto',
    'analysis.ai_insights': 'Phân Tích AI',
    'analysis.ai_description': 'Dự báo xu hướng và khuyến nghị giao dịch bằng trí tuệ nhân tạo',
    'analysis.refresh': 'Làm mới',
    'analysis.market_analysis': 'Phân tích thị trường',
    'analysis.analyzing': 'Đang phân tích...',
    'analysis.confidence': 'Độ tin cậy',
    'analysis.risk_level': 'Mức rủi ro',
    'analysis.price_targets': 'Mục tiêu giá',
    'analysis.short_term': 'Ngắn hạn',
    'analysis.medium_term': 'Trung hạn',
    'analysis.key_factors': 'Yếu tố chính',
    'analysis.ai_recommendation': 'Khuyến nghị AI',
    'analysis.analysis_type': 'Loại phân tích',
    'analysis.updated': 'Cập nhật',
    'analysis.error_no_data': 'Chưa có dữ liệu phân tích. Nhấn "Làm mới" để tạo.',
    'analysis.trading_recommendations': 'Khuyến nghị giao dịch',
    'analysis.login_required': 'Đăng nhập để xem khuyến nghị giao dịch cá nhân hóa',
    'analysis.creating_recommendations': 'Đang tạo khuyến nghị...',
    'analysis.risk_profile': 'Khẩu vị rủi ro',
    'analysis.conservative': 'Thận trọng',
    'analysis.moderate': 'Cân bằng',
    'analysis.aggressive': 'Mạo hiểm',
    'analysis.buy': 'MUA',
    'analysis.sell': 'BÁN',
    'analysis.hold': 'GIỮ',
    'analysis.reasoning': 'Lý do',
    'analysis.timeframe': 'Khung thời gian',
    'analysis.bitcoin_price': 'Giá Bitcoin',
    'analysis.risk_assessment': 'Đánh giá rủi ro',
    'analysis.error_no_recommendations': 'Chưa có khuyến nghị. Thử lại sau.',
    'analysis.sentiment_analysis': 'Phân tích cảm xúc tin tức',
    'analysis.sentiment_login_required': 'Đăng nhập để dùng công cụ phân tích cảm xúc',
    'analysis.news_input_label': 'Dán nội dung tin tức cần phân tích',
    'analysis.news_placeholder': 'Dán bài báo, tweet hoặc tin tức về thị trường crypto...',
    'analysis.analyzing_sentiment': 'Đang phân tích cảm xúc...',
    'analysis.analyze_sentiment': 'Phân tích cảm xúc',
    'analysis.sentiment_results': 'Kết quả phân tích',
    'analysis.sentiment_summary': 'Tóm tắt',
    'analysis.analyzed_at': 'Phân tích lúc',

    // Hero Section
    'hero.title': 'HHD Coin – Hệ sinh thái tài sản số, AI và tri thức học thuật',
    'hero.description': 'Kết nối tài sản số, trí tuệ nhân tạo và tri thức học thuật trên nền tảng blockchain — minh bạch, an toàn và hướng tới cộng đồng tri thức.',
    'hero.cta.invest': 'Bắt đầu đầu tư',
    'hero.cta.demo': 'Demo AI',
    'hero.cta.explore': 'Khám phá HHD Coin',
    'hero.cta.whitepaper': 'Đọc Whitepaper',
    'hero.cta.register': 'Tạo tài khoản',

    // Founder Section
    'founder.label': 'Nhà sáng lập',
    'founder.name': 'PGS.TS. Đỗ Hữu Hải',
    'founder.role1': 'Phó Giáo sư · Tiến sĩ',
    'founder.role2': 'Chuyên gia kinh tế',
    'founder.desc': 'Chuyên gia tư vấn chiến lược và chuyển đổi số. Nhà nghiên cứu kinh tế, AI & Blockchain — kiến tạo hệ sinh thái tri thức số HHD.',
    'founder.btn_profile': 'Hồ sơ khoa học',
    'founder.btn_research': 'Công trình nghiên cứu',
    'founder.btn_scholar': 'Google Scholar',
    'hero.feature.security': 'Bảo mật tuyệt đối',
    'hero.feature.ai': 'AI dự báo',
    'hero.feature.realtime': 'Thời gian thực',
    'hero.price.title': 'Giá Bitcoin hiện tại',

    // News Items in Home
    'news.bitcoin_title': 'Bitcoin phá kỷ lục',
    'news.bitcoin_surge': 'Bitcoin tiếp tục tăng mạnh nhờ dòng vốn ETF tổ chức, CoinGecko ghi nhận khối lượng giao dịch tăng 185% trong 24h qua.',
    'news.ai_title': 'AI dự báo thị trường',
    'news.ai_prediction': 'HHDAI 2.0 dự báo Bitcoin đạt $125,000 trong 7 ngày tới với độ tin cậy 89%, dựa trên 11 mô hình kinh tế vĩ mô.',
    'news.mobile_title': 'App Mobile ra mắt',
    'news.mobile_app': 'HHDCoin App cho Android & iOS sắp ra mắt — quản lý danh mục, nhận cảnh báo giá và tham gia governance DAO mọi lúc mọi nơi.',

    // Investment Packages page title/description
    'packages.title': 'Các vòng bán Token HHD',
    'packages.description': 'Tham gia sớm để nhận giá ưu đãi — Seed $0.005 → Public $0.020. Tổng hard cap $25M trên BNB Smart Chain.',
    'packages.page.title': 'Gói đầu tư HHDCoin',
    'packages.page.description': 'Chọn gói đầu tư phù hợp với chiến lược của bạn — từ cơ bản đến VIP với lợi nhuận tối ưu từ AI và thị trường crypto.',

    // Features Section
    'features.title_prefix': 'Tại sao chọn',
    'features.description_prefix': 'Khác biệt của',
    'features.description_suffix': 'là nền tảng đầu tư thông minh, bảo mật và minh bạch nhất cho nhà đầu tư Việt Nam.',
    'features.ai.title': 'Phân tích AI thông minh',
    'features.ai.description': 'HHDAI 2.0 với 11 mô hình kinh tế vĩ mô — dự báo xu hướng, phân tích rủi ro và đề xuất giao dịch tối ưu theo thời gian thực.',
    'features.speed.title': 'Tốc độ & Hiệu suất',
    'features.speed.description': 'BNB Smart Chain với 3,000+ TPS, phí giao dịch < $0.01 — đảm bảo mọi lệnh được thực thi ngay lập tức.',
    'features.analysis.title': 'Phân tích đa tài sản',
    'features.analysis.description': 'Theo dõi BTC, ETH, BNB, SOL, XRP, HHD và 100+ tài sản — biểu đồ nến, RSI, MACD, Bollinger Bands đầy đủ.',
    'features.free.title': 'Miễn phí & Mở',
    'features.free.description': 'Đăng ký miễn phí, không phí ẩn. Staking HHD để mở khóa tính năng nâng cao và tăng APY lên tới 55%.',

    // Login / Register
    'login.title': 'Đăng nhập',
    'login.subtitle': 'Chào mừng trở lại với HHDCoin',
    'login.username_label': 'Tên đăng nhập',
    'login.username_placeholder': 'Nhập tên đăng nhập',
    'login.password_label': 'Mật khẩu',
    'login.password_placeholder': 'Nhập mật khẩu',
    'login.login_button': 'Đăng nhập',
    'login.logging_in': 'Đang đăng nhập...',
    'login.or': 'Hoặc',
    'login.no_account': 'Chưa có tài khoản?',
    'login.register_now': 'Đăng ký ngay',
    'login.demo_accounts': 'Tài khoản dùng thử',
    'login.admin_demo': 'Quản trị:',
    'login.member_demo': 'Thành viên:',
    'login.username_min_error': 'Tên đăng nhập tối thiểu 3 ký tự',
    'login.password_min_error': 'Mật khẩu tối thiểu 6 ký tự',
    'login.success_title': 'Đăng nhập thành công',
    'login.success_description': 'Chào mừng bạn quay lại!',
    'login.back_home': 'Về trang chủ',
    'register.title': 'Đăng ký tài khoản',
    'register.subtitle': 'Tạo tài khoản đầu tư HHDCoin',
    'register.full_name_label': 'Họ và tên',
    'register.full_name_placeholder': 'Nhập họ và tên',
    'register.username_label': 'Tên đăng nhập',
    'register.username_placeholder': 'Chọn tên đăng nhập',
    'register.email_label': 'Email (tùy chọn)',
    'register.email_placeholder': 'Nhập địa chỉ email',
    'register.password_label': 'Mật khẩu',
    'register.password_placeholder': 'Nhập mật khẩu',
    'register.confirm_password_label': 'Xác nhận mật khẩu',
    'register.confirm_password_placeholder': 'Nhập lại mật khẩu',
    'register.register_button': 'Đăng ký',
    'register.registering': 'Đang đăng ký...',
    'register.have_account': 'Đã có tài khoản?',
    'register.login_now': 'Đăng nhập',
    'register.username_min_error': 'Tên đăng nhập tối thiểu 3 ký tự',
    'register.password_min_error': 'Mật khẩu tối thiểu 6 ký tự',
    'register.full_name_min_error': 'Họ tên tối thiểu 2 ký tự',
    'register.email_invalid_error': 'Email không hợp lệ',
    'register.password_mismatch_error': 'Mật khẩu xác nhận không khớp',
    'register.success_title': 'Đăng ký thành công',
    'register.success_description': 'Tài khoản của bạn đã được tạo!',
    'register.back_home': 'Về trang chủ',

    // Common
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.cancel': 'Hủy',
    'common.save': 'Lưu',
    'common.edit': 'Chỉnh sửa',
    'common.delete': 'Xóa',
    'common.confirm': 'Xác nhận',
    'common.yes': 'Có',
    'common.no': 'Không',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.account_management': 'Account Management',
    'nav.news': 'News',
    'nav.analysis': 'Analysis',
    'nav.community': 'Community',
    'nav.investment_management': 'Investment Management',
    'nav.investment_utilities': 'Investment Utilities',
    'nav.investment_guide': 'Investment Guide',
    'nav.contact': 'Contact',
    'nav.packages': 'Packages',
    'nav.investment': 'Investment',

    // Investment Calculator - CRITICAL FIXES
    'calc.title': 'Smart Investment Calculator',
    'calc.description': 'Calculate Bitcoin investment profits with AI prediction and automatic risk analysis',
    'calc.form.title': 'Investment Calculation',
    'calc.form.amount': 'Investment Amount (VND)',
    'calc.form.amount_placeholder': 'Enter amount...',
    'calc.form.duration': 'Investment Duration',
    'calc.form.duration.months': 'months',
    'calc.form.duration.6': '6 months',
    'calc.form.duration.12': '12 months',
    'calc.form.duration.18': '18 months',
    'calc.form.duration.24': '24 months',
    'calc.form.package': 'Investment Package',
    'calc.package.basic': 'Basic',
    'calc.package.premium': 'Premium',
    'calc.package.vip': 'VIP',
    'calc.risk.level': 'Risk Level',
    'calc.risk.low': 'Low',
    'calc.risk.medium': 'Medium',
    'calc.risk.high': 'High',
    'calc.results.title': 'Forecast Results',
    'calc.results.investment': 'Total Investment',
    'calc.results.profit': 'Estimated Profit',
    'calc.results.total': 'Total Return',
    'calc.ai.prediction_title': 'AI Prediction',
    'calc.ai.trend': 'Strong Uptrend',
    'calc.ai.confidence': 'Confidence: 89%',
    'calc.ai.scenario': 'Strong Growth Scenario',
    'calc.ai.market_signals': 'Market Signals',
    'calc.ai.positive_signals': 'Positive',
    'calc.ai.neutral_signals': 'Neutral',
    'calc.ai.negative_signals': 'Negative',
    'calc.disclaimer.title': 'Important Notice',
    'calc.disclaimer.text': 'Calculation results are for reference only. Investment carries risks, values may increase or decrease.',
    'calc.cta': 'Start Investing Now',

    // Contact Support - CRITICAL FIXES
    'contact.title': 'Contact & Support',
    'contact.description': 'HHDcoin expert team is always ready to support you 24/7',
    'contact.live_support': 'Live Support',
    'contact.response_time': 'Response within 2 hours',
    'contact.support_247': '24/7 Support',
    'contact.ai_assistant': 'AI Assistant always available',
    'contact.support_options.live_chat': 'Live Chat',
    'contact.support_options.video_call': 'Video Call',
    'contact.support_options.faq': 'FAQ',
    'contact.support_options.guide': 'Guide',
    'contact.support_options.live_chat_subtitle': 'Online',
    'contact.support_options.video_call_subtitle': 'Schedule',
    'contact.support_options.faq_subtitle': 'Frequently Asked Questions',
    'contact.support_options.guide_subtitle': 'Detailed Documentation',
    'contact.info.title': 'Contact Information',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.privacy_policy': 'I agree with the privacy policy',
    'contact.privacy_required': 'Please agree with the privacy policy',
    'contact.all_fields_required': 'Please fill in all required fields',
    'contact.send_success': 'Message sent successfully!',
    'contact.send_error': 'Error sending message',

    // News Analysis - CRITICAL FIXES
    'news.title': 'News & Analysis',
    'news.description': 'Latest updates from Bitcoin market',
    'news.featured_article_title': '🚀 Bitcoin officially exceeds $150K: New historical record!',
    'news.featured_article_excerpt': 'For the first time in history, Bitcoin has broken the psychological threshold of $150,000, marking an important milestone for the crypto market. HHDcoin AI prediction accurately predicted this event with 94% confidence. Experts believe this is a crucial turning point for Bitcoin to become a global reserve asset...',
    'news.featured_category': 'In-depth Analysis',
    'news.time_ago': 'ago',
    'news.hours': 'hours',
    'news.minutes': 'minutes',
    'news.status.hot': 'Hot',
    'news.status.government': 'Government',
    'news.status.technology': 'Technology',
    'news.status.country': 'Country',
    'news.read_more': 'Read more',
    'news.view_all_news': 'View all news',
    'news.latest_updates': 'Latest updates from Bitcoin market',
    'news.breaking_news': 'Breaking News',
    'news.market_news': 'Market News',
    
    // News Items - NEW TRANSLATIONS
    'news.item1.title': '💰 BlackRock ETF reaches $100B AUM after Bitcoin exceeds $150K',
    'news.item2.title': '🏛️ El Salvador announces purchase of 1000 more BTC at $150K',
    'news.item3.title': '⚡ Lightning Network processes 10M transactions/day',
    'news.item4.title': '🌏 Japan considers Bitcoin as reserve asset',
    
    // Community Discussion Posts - NEW TRANSLATIONS
    'community.post1.user': 'Nguyen Hoang',
    'community.post1.title': 'Should we DCA Bitcoin in the current situation?',
    'community.post1.preview': 'With Bitcoin price fluctuating around $43K, what do you think about the DCA strategy...',
    'community.post2.user': 'HHDcoin AI Assistant',
    'community.post2.title': 'This week\'s market analysis report',
    'community.post2.preview': 'AI analysis shows Bitcoin has a 78% chance of price increase in the next 7 days based on...',
    'community.post3.user': 'Le Thanh',
    'community.post3.title': 'Technical analysis: Bull flag pattern is forming',
    'community.post3.preview': 'Looking at Bitcoin\'s 4H chart, I see a very clear bull flag pattern. Short-term target...',
    'community.reply_button.default': 'Reply',
    'community.reply_button.bot': 'View Full Report',

    // Market Analysis - CRITICAL FIXES
    'market.title': 'Market Analysis',
    'market.description': 'Bitcoin exceeds $150K - Technical analysis and market trends in historical bull run',
    'market.bitcoin_surges': '🚀 Bitcoin breaks all records - Reaches $152,500 ATH!',
    'market.realtime_updates': 'Real-time chart from CoinGecko & Binance - Updated every 30 seconds',
    'market.24h_high': '24h High',
    'market.24h_low': '24h Low',
    'market.24h_volume': '24h Volume',
    'market.24h_change': '24h Change',
    'market.chart_title': 'Bitcoin Price Chart',
    'market.technical_indicators': 'Technical Indicators',
    'market.rsi': 'RSI (14)',
    'market.macd': 'MACD',
    'market.ma_50_200': 'MA 50/200',
    'market.volume': 'Volume',
    'market.super_bull': 'Super Bull',
    'market.insights_title': 'AI Insights',
    'market.key_insights': 'Key Points',
    'market.institutional_adoption': 'Institutional adoption surges 340%',
    'market.technical_breakout': 'Technical breakout above $148K resistance',
    'market.bullish_momentum': 'Extremely strong bullish momentum with RSI > 70',
    'market.volume_surge': 'Trading volume up 185% from average',
    'market.ai_prediction': 'AI prediction for next 7 days',
    'market.bull_run_continues': 'Bull run continues with 91% probability',
    'market.target_range': 'Target: $165K - $180K',
    'market.support_level': 'Strong support at $145K',
    'market.view_detailed_analysis': 'View detailed analysis',

    // Community Section - CRITICAL FIXES
    'community.title': 'HHDcoin Community',
    'community.description': 'Connect with thousands of Bitcoin investors, share experiences and learn from experts',
    'community.community_stats': 'Community Statistics',
    'community.stats.members': 'Members',
    'community.stats.messages_today': 'Messages Today',
    'community.stats.experts': 'Experts',
    'community.stats.countries': 'Countries',
    'community.discussions.title': 'Featured Discussions',
    'community.view_all_discussions': 'View all discussions',
    'community.join_community': 'Join Community',
    'community.member_levels.vip': 'VIP Member',
    'community.member_levels.bot': 'BOT',
    'community.member_levels.expert': 'Expert Trader',
    'community.likes': 'likes',
    'community.replies': 'replies',
    'community.login_required': 'Please login to join discussions',

    // Investment Packages - CRITICAL FIXES
    'packages.loading_message': 'Loading investment packages...',
    'packages.popular': 'MOST POPULAR',
    'packages.profit': 'Annual Profit',
    'packages.features': 'Features',
    'packages.contact_for_investment': 'Contact for investment consultation',
    'packages.select': 'Select This Package',

    // Pages - CRITICAL FIXES
    'pages.news.title': 'News & Analysis',
    'pages.news.subtitle': 'Latest news updates on Bitcoin and cryptocurrency market',
    'pages.investment_guide.title': 'HHDcoin Investment Guide',
    'pages.investment_guide.step_by_step': 'Detailed step-by-step guide to start your smart Bitcoin investment journey with AI and investment utilities',
    'pages.investment_guide.utilities_title': 'Smart Investment Utilities',

    // My Investments - CRITICAL FIXES
    'my_investments.title': 'Investment Management',
    'my_investments.login_required_title': 'Login Required',
    'my_investments.login_required_message': 'You need to login to view your investment information.',
    'my_investments.login_button': 'Login Now',
    'my_investments.no_investments_title': 'No Investments Yet',
    'my_investments.no_investments_message': 'You don\'t have any investments yet. Start investing today!',
    'my_investments.start_investing': 'Start Investing',
    'my_investments.portfolio_overview': 'Portfolio Overview',
    'my_investments.total_invested': 'Total Invested',
    'my_investments.current_value': 'Current Value',
    'my_investments.total_profit': 'Total Profit',
    'my_investments.investment_details': 'Investment Details',
    'my_investments.investment_amount': 'Investment Amount',
    'my_investments.profit_loss': 'Profit/Loss',
    'my_investments.profit_loss_percentage': 'Profit/Loss Percentage',
    'my_investments.start_date': 'Start Date',
    'my_investments.end_date': 'End Date',
    'my_investments.bitcoin_code': 'Bitcoin Code',
    'my_investments.status.active': 'Active',
    'my_investments.status.completed': 'Completed',
    'my_investments.status.cancelled': 'Cancelled',
    'my_investments.package_name': 'Investment Package',
    'my_investments.view_details': 'View Details',
    'my_investments.loading': 'Loading investment data...',
    'my_investments.error': 'Error loading data',
    'my_investments.details_button': 'Details',
    'my_investments.no_investments_description': 'Start your Bitcoin investment journey today',
    'my_investments.start_investing_button': 'Start Investing',
    'my_investments.investment_date': 'Investment Date',
    'my_investments.expected_profit': 'Expected Profit',
    'my_investments.loading_error': 'Error loading investment data',

    // Analysis page
    'analysis.title': 'Market Analysis',
    'analysis.description': 'AI-powered in-depth analysis — trends, recommendations, and real-time risk assessment',
    'analysis.features_title': 'Analysis Tools',
    'analysis.investment_chart': 'Investment Chart',
    'analytics.investment_chart': 'Track portfolio performance in real time',
    'analysis.market_share': 'Market Share',
    'analytics.market_share': 'Market cap distribution of top cryptocurrencies',
    'analysis.interest_rate_analysis': 'Interest Rate Analysis',
    'analytics.interest_rate': 'Interest rate impact on crypto markets',
    'analysis.ai_insights': 'AI Insights',
    'analysis.ai_description': 'AI-driven trend forecasts and trading recommendations',
    'analysis.refresh': 'Refresh',
    'analysis.market_analysis': 'Market Analysis',
    'analysis.analyzing': 'Analyzing...',
    'analysis.confidence': 'Confidence',
    'analysis.risk_level': 'Risk Level',
    'analysis.price_targets': 'Price Targets',
    'analysis.short_term': 'Short term',
    'analysis.medium_term': 'Medium term',
    'analysis.key_factors': 'Key Factors',
    'analysis.ai_recommendation': 'AI Recommendation',
    'analysis.analysis_type': 'Analysis Type',
    'analysis.updated': 'Updated',
    'analysis.error_no_data': 'No analysis data yet. Click "Refresh" to generate.',
    'analysis.trading_recommendations': 'Trading Recommendations',
    'analysis.login_required': 'Log in to view personalized trading recommendations',
    'analysis.creating_recommendations': 'Creating recommendations...',
    'analysis.risk_profile': 'Risk Profile',
    'analysis.conservative': 'Conservative',
    'analysis.moderate': 'Moderate',
    'analysis.aggressive': 'Aggressive',
    'analysis.buy': 'BUY',
    'analysis.sell': 'SELL',
    'analysis.hold': 'HOLD',
    'analysis.reasoning': 'Reasoning',
    'analysis.timeframe': 'Timeframe',
    'analysis.bitcoin_price': 'Bitcoin Price',
    'analysis.risk_assessment': 'Risk Assessment',
    'analysis.error_no_recommendations': 'No recommendations yet. Try again later.',
    'analysis.sentiment_analysis': 'News Sentiment Analysis',
    'analysis.sentiment_login_required': 'Log in to use the sentiment analysis tool',
    'analysis.news_input_label': 'Paste news content to analyze',
    'analysis.news_placeholder': 'Paste an article, tweet, or crypto market news...',
    'analysis.analyzing_sentiment': 'Analyzing sentiment...',
    'analysis.analyze_sentiment': 'Analyze Sentiment',
    'analysis.sentiment_results': 'Analysis Results',
    'analysis.sentiment_summary': 'Summary',
    'analysis.analyzed_at': 'Analyzed at',

    // Hero Section
    'hero.title': 'HHD Coin – Ecosystem of Digital Assets, AI and Academic Knowledge',
    'hero.description': 'Connecting digital assets, artificial intelligence and academic knowledge on a blockchain platform — transparent, secure and community-driven.',
    'hero.cta.invest': 'Start Investing',
    'hero.cta.demo': 'Demo AI',
    'hero.cta.explore': 'Explore HHD Coin',
    'hero.cta.whitepaper': 'Read Whitepaper',
    'hero.cta.register': 'Create Account',

    // Founder Section
    'founder.label': 'Founder',
    'founder.name': 'Assoc. Prof. Dr. Do Huu Hai',
    'founder.role1': 'Associate Professor · PhD',
    'founder.role2': 'Economist',
    'founder.desc': 'Strategy & digital transformation advisor. Researcher in Economics, AI & Blockchain — building the HHD digital knowledge ecosystem.',
    'founder.btn_profile': 'Academic Profile',
    'founder.btn_research': 'Research Works',
    'founder.btn_scholar': 'Google Scholar',
    'hero.feature.security': 'Top Security',
    'hero.feature.ai': 'AI Prediction',
    'hero.feature.realtime': 'Real-time',
    'hero.price.title': 'Current Bitcoin Price',

    // News Items in Home
    'news.bitcoin_title': 'Bitcoin breaks record',
    'news.bitcoin_surge': 'Bitcoin surges on institutional ETF inflows. CoinGecko records 185% volume surge in the last 24 hours.',
    'news.ai_title': 'AI market forecast',
    'news.ai_prediction': 'HHDAI 2.0 forecasts Bitcoin at $125,000 in 7 days with 89% confidence, based on 11 macroeconomic models.',
    'news.mobile_title': 'Mobile App launching',
    'news.mobile_app': 'HHDCoin App for Android & iOS coming soon — manage portfolios, set price alerts and participate in governance DAO on the go.',

    // Investment Packages
    'packages.title': 'HHD Token Sale Rounds',
    'packages.description': 'Join early for the best price — Seed $0.005 → Public $0.020. Total hard cap $25M on BNB Smart Chain.',
    'packages.page.title': 'HHDCoin Investment Packages',
    'packages.page.description': 'Choose the investment package that fits your strategy — from basic to VIP with optimized returns from AI and crypto markets.',

    // Features Section
    'features.title_prefix': 'Why choose',
    'features.description_prefix': "What makes",
    'features.description_suffix': 'the smartest, most secure and transparent investment platform for Vietnamese investors.',
    'features.ai.title': 'Smart AI Analysis',
    'features.ai.description': 'HHDAI 2.0 with 11 macroeconomic models — forecasts trends, analyses risk and suggests optimal trades in real-time.',
    'features.speed.title': 'Speed & Performance',
    'features.speed.description': 'BNB Smart Chain with 3,000+ TPS, fees < $0.01 — ensures every order executes instantly.',
    'features.analysis.title': 'Multi-Asset Analysis',
    'features.analysis.description': 'Track BTC, ETH, BNB, SOL, XRP, HHD and 100+ assets — candlestick charts, RSI, MACD, Bollinger Bands.',
    'features.free.title': 'Free & Open',
    'features.free.description': 'Register for free, no hidden fees. Stake HHD to unlock advanced features and boost APY up to 55%.',

    // Login / Register
    'login.title': 'Sign In',
    'login.subtitle': 'Welcome back to HHDCoin',
    'login.username_label': 'Username',
    'login.username_placeholder': 'Enter your username',
    'login.password_label': 'Password',
    'login.password_placeholder': 'Enter your password',
    'login.login_button': 'Sign In',
    'login.logging_in': 'Signing in...',
    'login.or': 'Or',
    'login.no_account': "Don't have an account?",
    'login.register_now': 'Register now',
    'login.demo_accounts': 'Demo accounts',
    'login.admin_demo': 'Admin:',
    'login.member_demo': 'Member:',
    'login.username_min_error': 'Username must be at least 3 characters',
    'login.password_min_error': 'Password must be at least 6 characters',
    'login.success_title': 'Signed in successfully',
    'login.success_description': 'Welcome back!',
    'login.back_home': 'Back to home',
    'register.title': 'Create Account',
    'register.subtitle': 'Create your HHDCoin investment account',
    'register.full_name_label': 'Full Name',
    'register.full_name_placeholder': 'Enter your full name',
    'register.username_label': 'Username',
    'register.username_placeholder': 'Choose a username',
    'register.email_label': 'Email (optional)',
    'register.email_placeholder': 'Enter your email',
    'register.password_label': 'Password',
    'register.password_placeholder': 'Enter your password',
    'register.confirm_password_label': 'Confirm Password',
    'register.confirm_password_placeholder': 'Re-enter your password',
    'register.register_button': 'Register',
    'register.registering': 'Registering...',
    'register.have_account': 'Already have an account?',
    'register.login_now': 'Sign in',
    'register.username_min_error': 'Username must be at least 3 characters',
    'register.password_min_error': 'Password must be at least 6 characters',
    'register.full_name_min_error': 'Full name must be at least 2 characters',
    'register.email_invalid_error': 'Invalid email address',
    'register.password_mismatch_error': 'Passwords do not match',
    'register.success_title': 'Registered successfully',
    'register.success_description': 'Your account has been created!',
    'register.back_home': 'Back to home',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('vi');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'vi' || savedLanguage === 'en')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const dict = translations[language] as Record<string, string>;
    let translation = dict[key] ?? key;

    if (params) {
      Object.entries(params).forEach(([paramKey, value]) => {
        translation = translation.replace(new RegExp(`{${paramKey}}`, 'g'), String(value));
      });
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}